= Act with Prudence<<sự thận trọng>>

"Whatever you undertake<<đảm nhận>>, act with prudence and consider the consequences<<hậu quả>>"
-- Anon

No matter how comfortable a schedule looks at the beginning of an iteration, you can't avoid being under pressure some of the time. If you find yourself having to choose between "doing it right" and "doing it quick" it is often appealing<<hấp dẫn>> to "do it quick" on the understanding that you'll come back and fix it later. When you make this promise to yourself, your team, and your customer, you mean it. But all too often the next iteration brings new problems and you become focused on them. This sort of deferred<<hoãn lại>> work is known as technical debt and it is not your friend. Specifically, Martin Fowler calls this deliberate<<có chủ ý
​>> technical debt in his http://martinfowler.com/bliki/TechnicalDebtQuadrant.html[taxonomy<<phân loại học>> of technical debt], which should not be confused with inadvertent<<vô tình>> technical debt.

Technical debt is like a loan: You benefit from it in the short-term, but you have to pay interest on it until it is fully paid off. Shortcuts in the code make it harder to add features or refactor your code. They are breeding grounds<<nơi sinh sản>> for defects<<khiếm khuyết>> and brittle<<mỏng mảnh>> test cases. The longer you leave it, the worse it gets. By the time you get around to undertaking the original fix there may be a whole stack of not-quite-right<<không hoàn toàn đúng>> design choices layered<<nhiều lớp>> on top of the original problem making the code much harder to refactor and correct. In fact, it is often only when things have got so bad that you must fix it, that you actually do go back to fix it. And by then it is often so hard to fix that you really can't afford the time or the risk.

There are times when you must incur<<gánh chịu
​>> technical debt to meet a deadline or implement a thin slice of a feature. Try not to be in this position, but if the situation absolutely demands <<yêu cầu>> it, then go ahead. But (and this is a big BUT) you must track technical debt and pay it back quickly or things go rapidly downhill<<xuống dốc>>. As soon as you make the decision to compromise<<thỏa hiệp>>, write a task card or log it in your issue tracking system to ensure that it does not get forgotten.

If you schedule repayment of the debt in the next iteration, the cost will be minimal. Leaving the debt unpaid will accrue<<tích lũy>> interest and that interest should be tracked to make the cost visible. This will emphasize<<nhấn mạnh>> the effect on business value of the project's technical debt and enables appropriate prioritization of the repayment. The choice of how to calculate and track the interest will depend on the particular project, but track it you must.

Pay off technical debt as soon as possible. It would be imprudent<<bất cẩn>> to do otherwise.

By http://programmer.97things.oreilly.com/wiki/index.php/Seb_Rose[Seb Rose]